/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsluno.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsluno.myDsl.MyDslPackage;
import org.xtext.example.mydsluno.myDsl.Pioche;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pioche</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.impl.PiocheImpl#getUnefois <em>Unefois</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PiocheImpl extends MinimalEObjectImpl.Container implements Pioche
{
  /**
   * The cached value of the '{@link #getUnefois() <em>Unefois</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnefois()
   * @generated
   * @ordered
   */
  protected EList<String> unefois;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PiocheImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PIOCHE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getUnefois()
  {
    if (unefois == null)
    {
      unefois = new EDataTypeEList<String>(String.class, this, MyDslPackage.PIOCHE__UNEFOIS);
    }
    return unefois;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PIOCHE__UNEFOIS:
        return getUnefois();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PIOCHE__UNEFOIS:
        getUnefois().clear();
        getUnefois().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PIOCHE__UNEFOIS:
        getUnefois().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PIOCHE__UNEFOIS:
        return unefois != null && !unefois.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (unefois: ");
    result.append(unefois);
    result.append(')');
    return result.toString();
  }

} //PiocheImpl
