/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsluno.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pioche</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Pioche#getUnefois <em>Unefois</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getPioche()
 * @model
 * @generated
 */
public interface Pioche extends EObject
{
  /**
   * Returns the value of the '<em><b>Unefois</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unefois</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getPioche_Unefois()
   * @model unique="false"
   * @generated
   */
  EList<String> getUnefois();

} // Pioche
