/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsluno.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getPioche <em>Pioche</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getPoser <em>Poser</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getMain <em>Main</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getCartespe <em>Cartespe</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getTemps <em>Temps</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getTas <em>Tas</em>}</li>
 *   <li>{@link org.xtext.example.mydsluno.myDsl.Uno#getNbcarte <em>Nbcarte</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno()
 * @model
 * @generated
 */
public interface Uno extends EObject
{
  /**
   * Returns the value of the '<em><b>Pioche</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsluno.myDsl.Pioche}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pioche</em>' containment reference list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Pioche()
   * @model containment="true"
   * @generated
   */
  EList<Pioche> getPioche();

  /**
   * Returns the value of the '<em><b>Poser</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Poser</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Poser()
   * @model unique="false"
   * @generated
   */
  EList<String> getPoser();

  /**
   * Returns the value of the '<em><b>Main</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Main()
   * @model unique="false"
   * @generated
   */
  EList<String> getMain();

  /**
   * Returns the value of the '<em><b>Cartespe</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartespe</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Cartespe()
   * @model unique="false"
   * @generated
   */
  EList<String> getCartespe();

  /**
   * Returns the value of the '<em><b>Temps</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Temps()
   * @model unique="false"
   * @generated
   */
  EList<String> getTemps();

  /**
   * Returns the value of the '<em><b>Tas</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tas</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Tas()
   * @model unique="false"
   * @generated
   */
  EList<String> getTas();

  /**
   * Returns the value of the '<em><b>Nbcarte</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nbcarte</em>' attribute list.
   * @see org.xtext.example.mydsluno.myDsl.MyDslPackage#getUno_Nbcarte()
   * @model unique="false"
   * @generated
   */
  EList<String> getNbcarte();

} // Uno
